version: '3.8'

services:
  ecommerce:
    image: jmbilbao25/qr-ecommerce-app:latest
    container_name: ecommerce-app
    ports:
      - "80:80"
    environment:
      - BANK_PUBLIC_BASE=${BANK_PUBLIC_BASE:-http://3.84.196.154}
      - DB_HOST=host.docker.internal
      - DB_NAME=${DB_NAME:-ecomdb}
      - DB_USER=${DB_USER:-ecomuser}
      - DB_PASSWORD=${DB_PASSWORD:-devpass}
      - USE_SQLITE=${USE_SQLITE:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - ecom-net

networks:
  ecom-net:
