pipeline { 
  agent any 
  environment { 
    // Docker Hub Repository
    IMAGE = "jmbilbao25/qr-ecommerce-app" 
    TAG   = "${env.GIT_COMMIT ? env.GIT_COMMIT.take(7) : 'latest'}"
    
    // Target deployment EC2 IP
    EC2_IP = "100.59.16.39" // TODO: Replace with actual Ecom VM IP
    EC2_USER = "ubuntu"
  } 
  stages { 
    stage('Build Docker Image') { 
      steps { 
        sh 'docker build -t $IMAGE:$TAG -t $IMAGE:latest ./ecommerce-app' 
      } 
    } 
    stage('Push to Docker Hub') { 
      steps { 
        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
          sh 'docker push $IMAGE:$TAG'
          sh 'docker push $IMAGE:latest'
        }
      } 
    } 
 
    stage('Deploy to EC2') { 
      steps { 
        sshagent(credentials: ['ec2-ssh-key-ecom']) {
          sh '''
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP "if [ ! -d ~/Banking-App ]; then git clone https://github.com/jmbilbao25/Banking-App.git ~/Banking-App; fi && cd ~/Banking-App && git pull && cd ecommerce-app && sudo docker compose -f docker-compose.ecom.yml pull ecommerce && sudo docker compose -f docker-compose.ecom.yml up -d ecommerce"
          '''
        }
      } 
    } 
  } 
}
