events {}

http {
  server {                       # shop.<VM_IP>.nip.io
    listen 80;
    server_name shop.*;
    location / { proxy_pass http://ecommerce:5000; proxy_set_header Host $host; }
  }
  server {                       # bank.<VM_IP>.nip.io
    listen 80;
    server_name bank.*;
    location / { proxy_pass http://banking:5001; proxy_set_header Host $host; }
  }
  server { listen 80 default_server; return 404; }
}
