pipeline { 
  agent any 
  environment { 
    // Docker Hub Repository
    IMAGE = "jmbilbao25/qr-banking-app" 
    TAG   = "${env.GIT_COMMIT ? env.GIT_COMMIT.take(7) : 'latest'}"
    
    // Target deployment EC2 IP
    EC2_IP = "44.204.212.148" // TODO: Replace with actual Bank VM IP
    EC2_USER = "ubuntu"
  } 
  stages { 
    stage('Build Docker Image') { 
      steps { 
        sh 'docker build -t $IMAGE:$TAG -t $IMAGE:latest ./banking-app' 
      } 
    } 
    stage('Push to Docker Hub') { 
      steps { 
        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
          sh 'docker push $IMAGE:$TAG'
          sh 'docker push $IMAGE:latest'
        }
      } 
    } 
    stage('Deploy to EC2') { 
      steps { 
        sshagent(credentials: ['ec2-ssh-key']) {
          sh '''
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP "if [ ! -d ~/Banking-App ]; then git clone https://github.com/jmbilbao25/Banking-App.git ~/Banking-App; fi && cd ~/Banking-App && git pull && cd banking-app && sudo docker compose -f docker-compose.bank.yml pull banking && sudo docker compose -f docker-compose.bank.yml up -d banking nginx"
          '''
        }
      } 
    } 
  } 
}
