pipeline { 
  agent any 
  environment { 
    // Docker Hub Repository
    IMAGE = "jmbilbao25/qr-banking-app" 
    TAG   = "${env.GIT_COMMIT ? env.GIT_COMMIT.take(7) : 'latest'}"
    
    // Target deployment EC2 IP
    EC2_IP = "3.84.196.154" // TODO: Replace with actual Bank VM IP
    EC2_USER = "ubuntu"
  } 
  stages { 
    stage('Build Docker Image') { 
      steps { 
        sh 'docker build -t $IMAGE:$TAG -t $IMAGE:latest ./banking-app' 
      } 
    } 
    stage('Push to Docker Hub') { 
      steps { 
        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
          sh 'docker push $IMAGE:$TAG'
          sh 'docker push $IMAGE:latest'
        }
      } 
    } 
    stage('Deploy to Dev/Test (ACI)') { 
      steps { 
        withCredentials([usernamePassword(credentialsId: 'azure-credentials', passwordVariable: 'AZ_PASS', usernameVariable: 'AZ_USER'), string(credentialsId: 'azure-tenant-id', variable: 'AZ_TENANT')]) {
          sh 'az login --service-principal -u $AZ_USER -p $AZ_PASS --tenant $AZ_TENANT'
          sh 'az container create --resource-group rg-azuser7669_mml.local-aafPZ --name banking-dev --image $IMAGE:$TAG --os-type Linux --cpu 1 --memory 1 --dns-name-label bank-dev-${BUILD_NUMBER} --ports 80 --environment-variables USE_SQLITE=true ECOM_CALLBACK_BASE=http://ecom-dev-${BUILD_NUMBER}.centralindia.azurecontainer.io --restart-policy Always'
        }
      } 
    } 
    stage('Deploy to EC2') { 
      steps { 
        sshagent(credentials: ['ec2-ssh-key']) {
          sh '''
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP "if [ ! -d ~/Banking-App ]; then git clone https://github.com/jmbilbao25/Banking-App.git ~/Banking-App; fi && cd ~/Banking-App && git pull && cd banking-app && sudo docker compose -f docker-compose.bank.yml pull banking && sudo docker compose -f docker-compose.bank.yml up -d banking"
          '''
        }
      } 
    } 
  } 
}
